export const countryList = [
  { name: "Afghanistan", code: "AF", flagEmoji: "🇦🇫", phoneCode: "+93" },
  { name: "Albania", code: "AL", flagEmoji: "🇦🇱", phoneCode: "+355" },
  { name: "Algeria", code: "DZ", flagEmoji: "🇩🇿", phoneCode: "+213" },
  { name: "Andorra", code: "AD", flagEmoji: "🇦🇩", phoneCode: "+376" },
  { name: "Angola", code: "AO", flagEmoji: "🇦🇴", phoneCode: "+244" },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    flagEmoji: "🇦🇬",
    phoneCode: "+1-268",
  },
  { name: "Argentina", code: "AR", flagEmoji: "🇦🇷", phoneCode: "+54" },
  { name: "Armenia", code: "AM", flagEmoji: "🇦🇲", phoneCode: "+374" },
  { name: "Australia", code: "AU", flagEmoji: "🇦🇺", phoneCode: "+61" },
  { name: "Austria", code: "AT", flagEmoji: "🇦🇹", phoneCode: "+43" },
  { name: "Azerbaijan", code: "AZ", flagEmoji: "🇦🇿", phoneCode: "+994" },
  { name: "Bahamas", code: "BS", flagEmoji: "🇧🇸", phoneCode: "+1-242" },
  { name: "Bahrain", code: "BH", flagEmoji: "🇧🇭", phoneCode: "+973" },
  { name: "Bangladesh", code: "BD", flagEmoji: "🇧🇩", phoneCode: "+880" },
  { name: "Barbados", code: "BB", flagEmoji: "🇧🇧", phoneCode: "+1-246" },
  { name: "Belarus", code: "BY", flagEmoji: "🇧🇾", phoneCode: "+375" },
  { name: "Belgium", code: "BE", flagEmoji: "🇧🇪", phoneCode: "+32" },
  { name: "Belize", code: "BZ", flagEmoji: "🇧🇿", phoneCode: "+501" },
  { name: "Benin", code: "BJ", flagEmoji: "🇧🇯", phoneCode: "+229" },
  { name: "Bhutan", code: "BT", flagEmoji: "🇧🇹", phoneCode: "+975" },
  { name: "Bolivia", code: "BO", flagEmoji: "🇧🇴", phoneCode: "+591" },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    flagEmoji: "🇧🇦",
    phoneCode: "+387",
  },
  { name: "Botswana", code: "BW", flagEmoji: "🇧🇼", phoneCode: "+267" },
  { name: "Brazil", code: "BR", flagEmoji: "🇧🇷", phoneCode: "+55" },
  { name: "Brunei", code: "BN", flagEmoji: "🇧🇳", phoneCode: "+673" },
  { name: "Bulgaria", code: "BG", flagEmoji: "🇧🇬", phoneCode: "+359" },
  { name: "Burkina Faso", code: "BF", flagEmoji: "🇧🇫", phoneCode: "+226" },
  { name: "Burundi", code: "BI", flagEmoji: "🇧🇮", phoneCode: "+257" },
  { name: "Cambodia", code: "KH", flagEmoji: "🇰🇭", phoneCode: "+855" },
  { name: "Cameroon", code: "CM", flagEmoji: "🇨🇲", phoneCode: "+237" },
  { name: "Canada", code: "CA", flagEmoji: "🇨🇦", phoneCode: "+1" },
  { name: "Cape Verde", code: "CV", flagEmoji: "🇨🇻", phoneCode: "+238" },
  {
    name: "Central African Republic",
    code: "CF",
    flagEmoji: "🇨🇫",
    phoneCode: "+236",
  },
  { name: "Chad", code: "TD", flagEmoji: "🇹🇩", phoneCode: "+235" },
  { name: "Chile", code: "CL", flagEmoji: "🇨🇱", phoneCode: "+56" },
  { name: "China", code: "CN", flagEmoji: "🇨🇳", phoneCode: "+86" },
  { name: "Colombia", code: "CO", flagEmoji: "🇨🇴", phoneCode: "+57" },
  { name: "Comoros", code: "KM", flagEmoji: "🇰🇲", phoneCode: "+269" },
  { name: "Congo", code: "CG", flagEmoji: "🇨🇬", phoneCode: "+242" },
  { name: "Costa Rica", code: "CR", flagEmoji: "🇨🇷", phoneCode: "+506" },
  { name: "Croatia", code: "HR", flagEmoji: "🇭🇷", phoneCode: "+385" },
  { name: "Cuba", code: "CU", flagEmoji: "🇨🇺", phoneCode: "+53" },
  { name: "Cyprus", code: "CY", flagEmoji: "🇨🇾", phoneCode: "+357" },
  { name: "Czech Republic", code: "CZ", flagEmoji: "🇨🇿", phoneCode: "+420" },
  { name: "Denmark", code: "DK", flagEmoji: "🇩🇰", phoneCode: "+45" },
  { name: "Djibouti", code: "DJ", flagEmoji: "🇩🇯", phoneCode: "+253" },
  { name: "Dominica", code: "DM", flagEmoji: "🇩🇲", phoneCode: "+1-767" },
  {
    name: "Dominican Republic",
    code: "DO",
    flagEmoji: "🇩🇴",
    phoneCode: "+1-809",
  },
  { name: "Ecuador", code: "EC", flagEmoji: "🇪🇨", phoneCode: "+593" },
  { name: "Egypt", code: "EG", flagEmoji: "🇪🇬", phoneCode: "+20" },
  { name: "El Salvador", code: "SV", flagEmoji: "🇸🇻", phoneCode: "+503" },
  { name: "Equatorial Guinea", code: "GQ", flagEmoji: "🇬🇶", phoneCode: "+240" },
  { name: "Eritrea", code: "ER", flagEmoji: "🇪🇷", phoneCode: "+291" },
  { name: "Estonia", code: "EE", flagEmoji: "🇪🇪", phoneCode: "+372" },
  { name: "Ethiopia", code: "ET", flagEmoji: "🇪🇹", phoneCode: "+251" },
  { name: "Fiji", code: "FJ", flagEmoji: "🇫🇯", phoneCode: "+679" },
  { name: "Finland", code: "FI", flagEmoji: "🇫🇮", phoneCode: "+358" },
  { name: "France", code: "FR", flagEmoji: "🇫🇷", phoneCode: "+33" },
  { name: "Gabon", code: "GA", flagEmoji: "🇬🇦", phoneCode: "+241" },
  { name: "Gambia", code: "GM", flagEmoji: "🇬🇲", phoneCode: "+220" },
  { name: "Georgia", code: "GE", flagEmoji: "🇬🇪", phoneCode: "+995" },
  { name: "Germany", code: "DE", flagEmoji: "🇩🇪", phoneCode: "+49" },
  { name: "Ghana", code: "GH", flagEmoji: "🇬🇭", phoneCode: "+233" },
  { name: "Greece", code: "GR", flagEmoji: "🇬🇷", phoneCode: "+30" },
  { name: "Grenada", code: "GD", flagEmoji: "🇬🇩", phoneCode: "+1-473" },
  { name: "Guatemala", code: "GT", flagEmoji: "🇬🇹", phoneCode: "+502" },
  { name: "Guinea", code: "GN", flagEmoji: "🇬🇳", phoneCode: "+224" },
  { name: "Guinea-Bissau", code: "GW", flagEmoji: "🇬🇼", phoneCode: "+245" },
  { name: "Guyana", code: "GY", flagEmoji: "🇬🇾", phoneCode: "+592" },
  { name: "Haiti", code: "HT", flagEmoji: "🇭🇹", phoneCode: "+509" },
  { name: "Honduras", code: "HN", flagEmoji: "🇭🇳", phoneCode: "+504" },
  { name: "Hong Kong", code: "HK", flagEmoji: "🇭🇰", phoneCode: "+852" },
  { name: "Hungary", code: "HU", flagEmoji: "🇭🇺", phoneCode: "+36" },
  { name: "Iceland", code: "IS", flagEmoji: "🇮🇸", phoneCode: "+354" },
  { name: "India", code: "IN", flagEmoji: "🇮🇳", phoneCode: "+91" },
  { name: "Indonesia", code: "ID", flagEmoji: "🇮🇩", phoneCode: "+62" },
  { name: "Iran", code: "IR", flagEmoji: "🇮🇷", phoneCode: "+98" },
  { name: "Iraq", code: "IQ", flagEmoji: "🇮🇶", phoneCode: "+964" },
  { name: "Ireland", code: "IE", flagEmoji: "🇮🇪", phoneCode: "+353" },
  { name: "Israel", code: "IL", flagEmoji: "🇮🇱", phoneCode: "+972" },
  { name: "Italy", code: "IT", flagEmoji: "🇮🇹", phoneCode: "+39" },
  { name: "Jamaica", code: "JM", flagEmoji: "🇯🇲", phoneCode: "+1-876" },
  { name: "Japan", code: "JP", flagEmoji: "🇯🇵", phoneCode: "+81" },
  { name: "Jordan", code: "JO", flagEmoji: "🇯🇴", phoneCode: "+962" },
  { name: "Kazakhstan", code: "KZ", flagEmoji: "🇰🇿", phoneCode: "+7" },
  { name: "Kenya", code: "KE", flagEmoji: "🇰🇪", phoneCode: "+254" },
  { name: "Kiribati", code: "KI", flagEmoji: "🇰🇮", phoneCode: "+686" },
  { name: "Kuwait", code: "KW", flagEmoji: "🇰🇼", phoneCode: "+965" },
  { name: "Kyrgyzstan", code: "KG", flagEmoji: "🇰🇬", phoneCode: "+996" },
  { name: "Laos", code: "LA", flagEmoji: "🇱🇦", phoneCode: "+856" },
  { name: "Latvia", code: "LV", flagEmoji: "🇱🇻", phoneCode: "+371" },
  { name: "Lebanon", code: "LB", flagEmoji: "🇱🇧", phoneCode: "+961" },
  { name: "Lesotho", code: "LS", flagEmoji: "🇱🇸", phoneCode: "+266" },
  { name: "Liberia", code: "LR", flagEmoji: "🇱🇷", phoneCode: "+231" },
  { name: "Libya", code: "LY", flagEmoji: "🇱🇾", phoneCode: "+218" },
  { name: "Liechtenstein", code: "LI", flagEmoji: "🇱🇮", phoneCode: "+423" },
  { name: "Lithuania", code: "LT", flagEmoji: "🇱🇹", phoneCode: "+370" },
  { name: "Luxembourg", code: "LU", flagEmoji: "🇱🇺", phoneCode: "+352" },
  { name: "Macao", code: "MO", flagEmoji: "🇲🇴", phoneCode: "+853" },
  { name: "Madagascar", code: "MG", flagEmoji: "🇲🇬", phoneCode: "+261" },
  { name: "Malawi", code: "MW", flagEmoji: "🇲🇼", phoneCode: "+265" },
  { name: "Malaysia", code: "MY", flagEmoji: "🇲🇾", phoneCode: "+60" },
  { name: "Maldives", code: "MV", flagEmoji: "🇲🇻", phoneCode: "+960" },
  { name: "Mali", code: "ML", flagEmoji: "🇲🇱", phoneCode: "+223" },
  { name: "Malta", code: "MT", flagEmoji: "🇲🇹", phoneCode: "+356" },
  { name: "Marshall Islands", code: "MH", flagEmoji: "🇲🇭", phoneCode: "+692" },
  { name: "Mauritania", code: "MR", flagEmoji: "🇲🇷", phoneCode: "+222" },
  { name: "Mauritius", code: "MU", flagEmoji: "🇲🇺", phoneCode: "+230" },
  { name: "Mexico", code: "MX", flagEmoji: "🇲🇽", phoneCode: "+52" },
  { name: "Micronesia", code: "FM", flagEmoji: "🇫🇲", phoneCode: "+691" },
  { name: "Moldova", code: "MD", flagEmoji: "🇲🇩", phoneCode: "+373" },
  { name: "Monaco", code: "MC", flagEmoji: "🇲🇨", phoneCode: "+377" },
  { name: "Mongolia", code: "MN", flagEmoji: "🇲🇳", phoneCode: "+976" },
  { name: "Montenegro", code: "ME", flagEmoji: "🇲🇪", phoneCode: "+382" },
  { name: "Morocco", code: "MA", flagEmoji: "🇲🇦", phoneCode: "+212" },
  { name: "Mozambique", code: "MZ", flagEmoji: "🇲🇿", phoneCode: "+258" },
  { name: "Myanmar", code: "MM", flagEmoji: "🇲🇲", phoneCode: "+95" },
  { name: "Namibia", code: "NA", flagEmoji: "🇳🇦", phoneCode: "+264" },
  { name: "Nauru", code: "NR", flagEmoji: "🇳🇷", phoneCode: "+674" },
  { name: "Nepal", code: "NP", flagEmoji: "🇳🇵", phoneCode: "+977" },
  { name: "Netherlands", code: "NL", flagEmoji: "🇳🇱", phoneCode: "+31" },
  { name: "New Zealand", code: "NZ", flagEmoji: "🇳🇿", phoneCode: "+64" },
  { name: "Nicaragua", code: "NI", flagEmoji: "🇳🇮", phoneCode: "+505" },
  { name: "Niger", code: "NE", flagEmoji: "🇳🇪", phoneCode: "+227" },
  { name: "Nigeria", code: "NG", flagEmoji: "🇳🇬", phoneCode: "+234" },
  { name: "North Korea", code: "KP", flagEmoji: "🇰🇵", phoneCode: "+850" },
  { name: "North Macedonia", code: "MK", flagEmoji: "🇲🇰", phoneCode: "+389" },
  { name: "Norway", code: "NO", flagEmoji: "🇳🇴", phoneCode: "+47" },
  { name: "Oman", code: "OM", flagEmoji: "🇴🇲", phoneCode: "+968" },
  { name: "Pakistan", code: "PK", flagEmoji: "🇵🇰", phoneCode: "+92" },
  { name: "Palau", code: "PW", flagEmoji: "🇵🇼", phoneCode: "+680" },
  { name: "Palestine", code: "PS", flagEmoji: "🇵🇸", phoneCode: "+970" },
  { name: "Panama", code: "PA", flagEmoji: "🇵🇦", phoneCode: "+507" },
  { name: "Papua New Guinea", code: "PG", flagEmoji: "🇵🇬", phoneCode: "+675" },
  { name: "Paraguay", code: "PY", flagEmoji: "🇵🇾", phoneCode: "+595" },
  { name: "Peru", code: "PE", flagEmoji: "🇵🇪", phoneCode: "+51" },
  { name: "Philippines", code: "PH", flagEmoji: "🇵🇭", phoneCode: "+63" },
  { name: "Poland", code: "PL", flagEmoji: "🇵🇱", phoneCode: "+48" },
  { name: "Portugal", code: "PT", flagEmoji: "🇵🇹", phoneCode: "+351" },
  { name: "Qatar", code: "QA", flagEmoji: "🇶🇦", phoneCode: "+974" },
  { name: "Romania", code: "RO", flagEmoji: "🇷🇴", phoneCode: "+40" },
  { name: "Russia", code: "RU", flagEmoji: "🇷🇺", phoneCode: "+7" },
  { name: "Rwanda", code: "RW", flagEmoji: "🇷🇼", phoneCode: "+250" },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    flagEmoji: "🇰🇳",
    phoneCode: "+1-869",
  },
  { name: "Saint Lucia", code: "LC", flagEmoji: "🇱🇨", phoneCode: "+1-758" },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    flagEmoji: "🇻🇨",
    phoneCode: "+1-784",
  },
  { name: "Samoa", code: "WS", flagEmoji: "🇼🇸", phoneCode: "+685" },
  { name: "San Marino", code: "SM", flagEmoji: "🇸🇲", phoneCode: "+378" },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    flagEmoji: "🇸🇹",
    phoneCode: "+239",
  },
  { name: "Saudi Arabia", code: "SA", flagEmoji: "🇸🇦", phoneCode: "+966" },
  { name: "Senegal", code: "SN", flagEmoji: "🇸🇳", phoneCode: "+221" },
  { name: "Serbia", code: "RS", flagEmoji: "🇷🇸", phoneCode: "+381" },
  { name: "Seychelles", code: "SC", flagEmoji: "🇸🇨", phoneCode: "+248" },
  { name: "Sierra Leone", code: "SL", flagEmoji: "🇸🇱", phoneCode: "+232" },
  { name: "Singapore", code: "SG", flagEmoji: "🇸🇬", phoneCode: "+65" },
  { name: "Slovakia", code: "SK", flagEmoji: "🇸🇰", phoneCode: "+421" },
  { name: "Slovenia", code: "SI", flagEmoji: "🇸🇮", phoneCode: "+386" },
  { name: "Solomon Islands", code: "SB", flagEmoji: "🇸🇧", phoneCode: "+677" },
  { name: "Somalia", code: "SO", flagEmoji: "🇸🇴", phoneCode: "+252" },
  { name: "South Africa", code: "ZA", flagEmoji: "🇿🇦", phoneCode: "+27" },
  { name: "South Korea", code: "KR", flagEmoji: "🇰🇷", phoneCode: "+82" },
  { name: "South Sudan", code: "SS", flagEmoji: "🇸🇸", phoneCode: "+211" },
  { name: "Spain", code: "ES", flagEmoji: "🇪🇸", phoneCode: "+34" },
  { name: "Sri Lanka", code: "LK", flagEmoji: "🇱🇰", phoneCode: "+94" },
  { name: "Sudan", code: "SD", flagEmoji: "🇸🇩", phoneCode: "+249" },
  { name: "Suriname", code: "SR", flagEmoji: "🇸🇷", phoneCode: "+597" },
  { name: "Sweden", code: "SE", flagEmoji: "🇸🇪", phoneCode: "+46" },
  { name: "Switzerland", code: "CH", flagEmoji: "🇨🇭", phoneCode: "+41" },
  { name: "Syria", code: "SY", flagEmoji: "🇸🇾", phoneCode: "+963" },
  { name: "Taiwan", code: "TW", flagEmoji: "🇹🇼", phoneCode: "+886" },
  { name: "Tajikistan", code: "TJ", flagEmoji: "🇹🇯", phoneCode: "+992" },
  { name: "Tanzania", code: "TZ", flagEmoji: "🇹🇿", phoneCode: "+255" },
  { name: "Thailand", code: "TH", flagEmoji: "🇹🇭", phoneCode: "+66" },
  { name: "Timor-Leste", code: "TL", flagEmoji: "🇹🇱", phoneCode: "+670" },
  { name: "Togo", code: "TG", flagEmoji: "🇹🇬", phoneCode: "+228" },
  { name: "Tonga", code: "TO", flagEmoji: "🇹🇴", phoneCode: "+676" },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    flagEmoji: "🇹🇹",
    phoneCode: "+1-868",
  },
  { name: "Tunisia", code: "TN", flagEmoji: "🇹🇳", phoneCode: "+216" },
  { name: "Turkey", code: "TR", flagEmoji: "🇹🇷", phoneCode: "+90" },
  { name: "Turkmenistan", code: "TM", flagEmoji: "🇹🇲", phoneCode: "+993" },
  { name: "Tuvalu", code: "TV", flagEmoji: "🇹🇻", phoneCode: "+688" },
  { name: "Uganda", code: "UG", flagEmoji: "🇺🇬", phoneCode: "+256" },
  { name: "Ukraine", code: "UA", flagEmoji: "🇺🇦", phoneCode: "+380" },
  {
    name: "United Arab Emirates",
    code: "AE",
    flagEmoji: "🇦🇪",
    phoneCode: "+971",
  },
  { name: "United Kingdom", code: "GB", flagEmoji: "🇬🇧", phoneCode: "+44" },
  { name: "United States", code: "US", flagEmoji: "🇺🇸", phoneCode: "+1" },
  { name: "Uruguay", code: "UY", flagEmoji: "🇺🇾", phoneCode: "+598" },
  { name: "Uzbekistan", code: "UZ", flagEmoji: "🇺🇿", phoneCode: "+998" },
  { name: "Vanuatu", code: "VU", flagEmoji: "🇻🇺", phoneCode: "+678" },
  { name: "Vatican City", code: "VA", flagEmoji: "🇻🇦", phoneCode: "+379" },
  { name: "Venezuela", code: "VE", flagEmoji: "🇻🇪", phoneCode: "+58" },
  { name: "Vietnam", code: "VN", flagEmoji: "🇻🇳", phoneCode: "+84" },
  { name: "Yemen", code: "YE", flagEmoji: "🇾🇪", phoneCode: "+967" },
  { name: "Zambia", code: "ZM", flagEmoji: "🇿🇲", phoneCode: "+260" },
  { name: "Zimbabwe", code: "ZW", flagEmoji: "🇿🇼", phoneCode: "+263" },
];
